# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7d39f84eec4e4f08eb32e6d352ea6c6991b8e0ede13e1a2967bba454deae2c8864426ba5ed3cc5795e6e51d1b893956d2f5c97568e4948de97ecb25783da389

test:
  secret_key_base: b59948665ad40d8e99fe259f5dbea02760de251df89dfef7ab003eaf93a5b8a6d97f1d271befd0349ffd0b19c6808fb637a26230598d1fab61976c112720b6a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
